### ISSUE TITLE
[PHP 8] Core check update test uses WordPress 4.4 which uses magic quotes

### ISSUE THREAD

**Issue by TimothyBJacobs** [wp-cli/core-command#172]
The `get_magic_quotes_gpc` has been removed in PHP 8. This means that when WP CLI tries to install WordPress 4.4, it can't be loaded because WordPress expects that function to exist.

As of WordPress 5.3, this function is no longer called. Perhaps the WordPress version could be switched from 4.4 to 5.3?

```
$ wp core check-update

    PHP Fatal error:  Uncaught Error: Call to undefined function get_magic_quotes_gpc() in /private/var/folders/7d/mcmynw4x60v3y8nwlfz3ppg80000gn/T/wp-cli-test-run-core-check-update.feature.3-5fac53a97a69a1.95269510/wp-includes/load.php:607
    Stack trace:
    #0 /Users/timothybjacobs/Workspace/wp-cli-dev/wp-cli/php/wp-settings-cli.php(339): wp_magic_quotes()
    #1 /Users/timothybjacobs/Workspace/wp-cli-dev/wp-cli/php/WP_CLI/Runner.php(1253): require('/Users/timothyb...')
    #2 /Users/timothybjacobs/Workspace/wp-cli-dev/wp-cli/php/WP_CLI/Runner.php(1172): WP_CLI\Runner->load_wordpress()
    #3 /Users/timothybjacobs/Workspace/wp-cli-dev/wp-cli/php/WP_CLI/Bootstrap/LaunchRunner.php(23): WP_CLI\Runner->start()
    #4 /Users/timothybjacobs/Workspace/wp-cli-dev/wp-cli/php/bootstrap.php(75): WP_CLI\Bootstrap\LaunchRunner->process(Object(WP_CLI\Bootstrap\BootstrapState))
    #5 /Users/timothybjacobs/Workspace/wp-cli-dev/wp-cli/php/wp-cli.php(27): WP_CLI\bootstrap()
    #6 /Users/timothybjacobs/Workspace/wp-cli-dev/wp-cli/php/boot-fs.php(17): require_once('/Users/timothyb...')
    #7 {main}
      thrown in /private/var/folders/7d/mcmynw4x60v3y8nwlfz3ppg80000gn/T/wp-cli-test-run-core-check-update.feature.3-5fac53a97a69a1.95269510/wp-includes/load.php on line 607
    Fatal error: Uncaught Error: Call to undefined function get_magic_quotes_gpc() in /private/var/folders/7d/mcmynw4x60v3y8nwlfz3ppg80000gn/T/wp-cli-test-run-core-check-update.feature.3-5fac53a97a69a1.95269510/wp-includes/load.php:607
    Stack trace:
    #0 /Users/timothybjacobs/Workspace/wp-cli-dev/wp-cli/php/wp-settings-cli.php(339): wp_magic_quotes()
    #1 /Users/timothybjacobs/Workspace/wp-cli-dev/wp-cli/php/WP_CLI/Runner.php(1253): require('/Users/timothyb...')
    #2 /Users/timothybjacobs/Workspace/wp-cli-dev/wp-cli/php/WP_CLI/Runner.php(1172): WP_CLI\Runner->load_wordpress()
    #3 /Users/timothybjacobs/Workspace/wp-cli-dev/wp-cli/php/WP_CLI/Bootstrap/LaunchRunner.php(23): WP_CLI\Runner->start()
    #4 /Users/timothybjacobs/Workspace/wp-cli-dev/wp-cli/php/bootstrap.php(75): WP_CLI\Bootstrap\LaunchRunner->process(Object(WP_CLI\Bootstrap\BootstrapState))
    #5 /Users/timothybjacobs/Workspace/wp-cli-dev/wp-cli/php/wp-cli.php(27): WP_CLI\bootstrap()
    #6 /Users/timothybjacobs/Workspace/wp-cli-dev/wp-cli/php/boot-fs.php(17): require_once('/Users/timothyb...')
    #7 {main}
      thrown in /private/var/folders/7d/mcmynw4x60v3y8nwlfz3ppg80000gn/T/wp-cli-test-run-core-check-update.feature.3-5fac53a97a69a1.95269510/wp-includes/load.php on line 607
    cwd: /var/folders/7d/mcmynw4x60v3y8nwlfz3ppg80000gn/T/wp-cli-test-run-core-check-update.feature.3-5fac53a97a69a1.95269510/
    run time: 0.29144096374512
    exit status: 255
    In step `When I run `wp core check-update`'.            # /Users/timothybjacobs/Workspace/wp-cli-dev/wp-cli-tests/features/steps/when.php:29
    From scenario `Check for update via Version Check API'. # features/core-check-update.feature:3
    Of feature `Check for more recent versions'.
```

**Comment by danielbachhuber** [comment]
Thanks for the report, @TimothyBJacobs 

Is this still valid?

**Comment by TimothyBJacobs** [comment]
No idea :) probably not. I think this was created when trying to get the test suite running on PHP 8. So it shouldn't be an issue any longer.

**Comment by danielbachhuber** [comment]
@TimothyBJacobs Awesome, thanks!

**Comment by stanislavdavid** [comment]
It is still not possible. I just try to upgrade one old site using wp-cli - not working same issue

**Comment by stanislavdavid** [comment]
I solved that by modifying source code of my wordpress site -
I append function_exists('get_magic_quotes_gpc') &&  before conditions

from 

`if (get_magic_quotes_gpc()) {
`
to 

`if (function_exists('get_magic_quotes_gpc') && get_magic_quotes_gpc()) {
`

to every location in wordpress
