### ISSUE TITLE
Core_Command::cleanup_extra_files() incorrectly deletes files on case-insensitive filesystems when an update changes the case of a file

### ISSUE THREAD

**Issue by pbiron** [wp-cli/core-command#195]
## Bug Report

- [X] Yes, I reviewed the [contribution guidelines](https://make.wordpress.org/cli/handbook/contributing/).
- [x] Yes, more specifically, I reviewed the guidelines on [how to write clear bug reports](https://make.wordpress.org/cli/handbook/bug-reports/).

**Describe the current, buggy behavior**

During the WP 5.9-beta1 release party, it was discovered that a number of files in the `Requests` library has their filenames changed only in case (e.g., `wp-includes/Requests/IRI.php` -> `wp-includes/Requests/Iri.php`.

When updating to 5.9-beta 1 via wp-cli on a machine with a case in-sensitive filesystem (e.g., Windows), those files are deleted in `Core_Command::cleanup_extra_files()` and that results in PHP fatal errors whenever core tries to use the Requests library.

**Describe what you would expect as the correct outcome**

I expect the detection of files to be deleted to be done in a case-insensitive manner.

**Let us know what environment you are running this on**

Windows 10

```
Cleaning up files...
File removed: wp-includes/Requests/Transport/fsockopen.php
File removed: wp-includes/Requests/Transport/cURL.php
File removed: wp-includes/Requests/Hooker.php
File removed: wp-includes/Requests/IPv6.php
File removed: wp-includes/Requests/Exception/Transport/cURL.php
File removed: wp-includes/Requests/Exception/HTTP.php
File removed: wp-includes/Requests/Exception/HTTP/502.php
File removed: wp-includes/Requests/Exception/HTTP/Unknown.php
File removed: wp-includes/Requests/Exception/HTTP/412.php
File removed: wp-includes/Requests/Exception/HTTP/408.php
File removed: wp-includes/Requests/Exception/HTTP/431.php
File removed: wp-includes/Requests/Exception/HTTP/501.php
File removed: wp-includes/Requests/Exception/HTTP/500.php
File removed: wp-includes/Requests/Exception/HTTP/407.php
File removed: wp-includes/Requests/Exception/HTTP/416.php
File removed: wp-includes/Requests/Exception/HTTP/428.php
File removed: wp-includes/Requests/Exception/HTTP/406.php
File removed: wp-includes/Requests/Exception/HTTP/504.php
File removed: wp-includes/Requests/Exception/HTTP/411.php
File removed: wp-includes/Requests/Exception/HTTP/414.php
File removed: wp-includes/Requests/Exception/HTTP/511.php
File removed: wp-includes/Requests/Exception/HTTP/410.php
File removed: wp-includes/Requests/Exception/HTTP/403.php
File removed: wp-includes/Requests/Exception/HTTP/400.php
File removed: wp-includes/Requests/Exception/HTTP/505.php
File removed: wp-includes/Requests/Exception/HTTP/413.php
File removed: wp-includes/Requests/Exception/HTTP/404.php
File removed: wp-includes/Requests/Exception/HTTP/306.php
File removed: wp-includes/Requests/Exception/HTTP/304.php
File removed: wp-includes/Requests/Exception/HTTP/405.php
File removed: wp-includes/Requests/Exception/HTTP/429.php
File removed: wp-includes/Requests/Exception/HTTP/417.php
File removed: wp-includes/Requests/Exception/HTTP/409.php
File removed: wp-includes/Requests/Exception/HTTP/402.php
File removed: wp-includes/Requests/Exception/HTTP/418.php
File removed: wp-includes/Requests/Exception/HTTP/305.php
File removed: wp-includes/Requests/Exception/HTTP/415.php
File removed: wp-includes/Requests/Exception/HTTP/401.php
File removed: wp-includes/Requests/Exception/HTTP/503.php
File removed: wp-includes/Requests/IRI.php
File removed: wp-includes/Requests/IDNAEncoder.php
File removed: wp-includes/Requests/SSL.php
File removed: wp-includes/Requests/Proxy/HTTP.php
File removed: wp-includes/blocks/post-content/editor.min.css
File removed: wp-includes/blocks/post-content/editor.css
File removed: wp-includes/blocks/post-content/editor-rtl.css
File removed: wp-includes/blocks/post-content/editor-rtl.min.css
File removed: wp-includes/blocks/heading/editor.min.css
File removed: wp-includes/blocks/heading/editor.css
File removed: wp-includes/blocks/heading/editor-rtl.css
File removed: wp-includes/blocks/heading/editor-rtl.min.css
File removed: wp-includes/blocks/query-title/editor.min.css
File removed: wp-includes/blocks/query-title/editor.css
File removed: wp-includes/blocks/query-title/editor-rtl.css
File removed: wp-includes/blocks/query-title/editor-rtl.min.css
File removed: wp-includes/blocks/tag-cloud/editor.min.css
File removed: wp-includes/blocks/tag-cloud/editor.css
File removed: wp-includes/blocks/tag-cloud/editor-rtl.css
File removed: wp-includes/blocks/tag-cloud/editor-rtl.min.css
59 files cleaned up.
```

**Provide a possible solution**

I think it should be relatively easy to fix by doing case folding (e.g., convert everything to lower case) before doing:

`$files_to_remove = array_diff( array_keys( $old_checksums ), array_keys( $new_checksums ) );`

**Comment by hellofromtonya** [comment]
I ran similar tests on macOS. [A Test Report was shared in Trac here](https://core.trac.wordpress.org/ticket/54547#comment:5). Copying to this issue.

## Test Report

Env:
* OS: macOS Big Sur
* Localhost: Local
* WP-CLI (through Local's site shell)
* Plugins: Core Rollback and Beta Tester

Steps:
1. Open the site shell through Local
2. Type: `wp core update --version=5.9-beta1`
3. Press enter/return key.
4. After update, check error logs and ensure all Requests files are present.

Results:
* 59 files clean up
```
Updating to version 5.9-beta1 (en_US)...
Downloading update from https://wordpress.org/wordpress-5.9-beta1.zip...
Unpacking the update...
Cleaning up files...
File removed: wp-includes/Requests/Transport/fsockopen.php
File removed: wp-includes/Requests/Transport/cURL.php
File removed: wp-includes/Requests/Hooker.php
File removed: wp-includes/Requests/IPv6.php
File removed: wp-includes/Requests/Exception/Transport/cURL.php
File removed: wp-includes/Requests/Exception/HTTP.php
File removed: wp-includes/Requests/Exception/HTTP/502.php
File removed: wp-includes/Requests/Exception/HTTP/Unknown.php
File removed: wp-includes/Requests/Exception/HTTP/412.php
File removed: wp-includes/Requests/Exception/HTTP/408.php
File removed: wp-includes/Requests/Exception/HTTP/431.php
File removed: wp-includes/Requests/Exception/HTTP/501.php
File removed: wp-includes/Requests/Exception/HTTP/500.php
File removed: wp-includes/Requests/Exception/HTTP/407.php
File removed: wp-includes/Requests/Exception/HTTP/416.php
File removed: wp-includes/Requests/Exception/HTTP/428.php
File removed: wp-includes/Requests/Exception/HTTP/406.php
File removed: wp-includes/Requests/Exception/HTTP/504.php
File removed: wp-includes/Requests/Exception/HTTP/411.php
File removed: wp-includes/Requests/Exception/HTTP/414.php
File removed: wp-includes/Requests/Exception/HTTP/511.php
File removed: wp-includes/Requests/Exception/HTTP/410.php
File removed: wp-includes/Requests/Exception/HTTP/403.php
File removed: wp-includes/Requests/Exception/HTTP/400.php
File removed: wp-includes/Requests/Exception/HTTP/505.php
File removed: wp-includes/Requests/Exception/HTTP/413.php
File removed: wp-includes/Requests/Exception/HTTP/404.php
File removed: wp-includes/Requests/Exception/HTTP/306.php
File removed: wp-includes/Requests/Exception/HTTP/304.php
File removed: wp-includes/Requests/Exception/HTTP/405.php
File removed: wp-includes/Requests/Exception/HTTP/429.php
File removed: wp-includes/Requests/Exception/HTTP/417.php
File removed: wp-includes/Requests/Exception/HTTP/409.php
File removed: wp-includes/Requests/Exception/HTTP/402.php
File removed: wp-includes/Requests/Exception/HTTP/418.php
File removed: wp-includes/Requests/Exception/HTTP/305.php
File removed: wp-includes/Requests/Exception/HTTP/415.php
File removed: wp-includes/Requests/Exception/HTTP/401.php
File removed: wp-includes/Requests/Exception/HTTP/503.php
File removed: wp-includes/Requests/IRI.php
File removed: wp-includes/Requests/IDNAEncoder.php
File removed: wp-includes/Requests/SSL.php
File removed: wp-includes/Requests/Proxy/HTTP.php
File removed: wp-includes/blocks/post-content/editor.min.css
File removed: wp-includes/blocks/post-content/editor.css
File removed: wp-includes/blocks/post-content/editor-rtl.css
File removed: wp-includes/blocks/post-content/editor-rtl.min.css
File removed: wp-includes/blocks/heading/editor.min.css
File removed: wp-includes/blocks/heading/editor.css
File removed: wp-includes/blocks/heading/editor-rtl.css
File removed: wp-includes/blocks/heading/editor-rtl.min.css
File removed: wp-includes/blocks/query-title/editor.min.css
File removed: wp-includes/blocks/query-title/editor.css
File removed: wp-includes/blocks/query-title/editor-rtl.css
File removed: wp-includes/blocks/query-title/editor-rtl.min.css
File removed: wp-includes/blocks/tag-cloud/editor.min.css
File removed: wp-includes/blocks/tag-cloud/editor.css
File removed: wp-includes/blocks/tag-cloud/editor-rtl.css
File removed: wp-includes/blocks/tag-cloud/editor-rtl.min.css
59 files cleaned up.
```

* error log in Local's `logs/php/error.log`

```
[01-Dec-2021 20:03:24 UTC] PHP Notice:  Constant WP_ENVIRONMENT_TYPE already defined in phar:///Applications/Local.app/Contents/Resources/extraResources/bin/wp-cli/wp-cli.phar/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(1231) : eval()'d code on line 71
[01-Dec-2021 20:03:24 UTC] PHP Stack trace:
[01-Dec-2021 20:03:24 UTC] PHP   1. {main}() /Applications/Local.app/Contents/Resources/extraResources/bin/wp-cli/wp-cli.phar:0
[01-Dec-2021 20:03:24 UTC] PHP   2. include() /Applications/Local.app/Contents/Resources/extraResources/bin/wp-cli/wp-cli.phar:4
[01-Dec-2021 20:03:24 UTC] PHP   3. include() phar:///Applications/Local.app/Contents/Resources/extraResources/bin/wp-cli/wp-cli.phar/php/boot-phar.php:11
[01-Dec-2021 20:03:24 UTC] PHP   4. WP_CLI\bootstrap() phar:///Applications/Local.app/Contents/Resources/extraResources/bin/wp-cli/wp-cli.phar/vendor/wp-cli/wp-cli/php/wp-cli.php:27
[01-Dec-2021 20:03:24 UTC] PHP   5. WP_CLI\Bootstrap\LaunchRunner->process() phar:///Applications/Local.app/Contents/Resources/extraResources/bin/wp-cli/wp-cli.phar/vendor/wp-cli/wp-cli/php/bootstrap.php:77
[01-Dec-2021 20:03:24 UTC] PHP   6. WP_CLI\Runner->start() phar:///Applications/Local.app/Contents/Resources/extraResources/bin/wp-cli/wp-cli.phar/vendor/wp-cli/wp-cli/php/WP_CLI/Bootstrap/LaunchRunner.php:23
[01-Dec-2021 20:03:24 UTC] PHP   7. WP_CLI\Runner->load_wordpress() phar:///Applications/Local.app/Contents/Resources/extraResources/bin/wp-cli/wp-cli.phar/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php:1192
[01-Dec-2021 20:03:24 UTC] PHP   8. eval() phar:///Applications/Local.app/Contents/Resources/extraResources/bin/wp-cli/wp-cli.phar/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php:1231
[01-Dec-2021 20:03:24 UTC] PHP   9. define() phar:///Applications/Local.app/Contents/Resources/extraResources/bin/wp-cli/wp-cli.phar/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(1231) : eval()'d code:71
```

* Go to a page in the admin area - Fatal error.

```
[01-Dec-2021 20:26:33 UTC] PHP Fatal error:  Uncaught Error: Class 'WpOrg\Requests\Iri' not found in ../Local/test/app/public/wp-includes/Requests/Requests.php:682
Stack trace:
#0 ../Local/test/app/public/wp-includes/Requests/Requests.php(452): WpOrg\Requests\Requests::set_defaults('https://api.wor...', Array, Array, 'POST', Array)
#1 ../Local/test/app/public/wp-includes/class-wp-http.php(394): WpOrg\Requests\Requests::request('https://api.wor...', Array, Array, 'POST', Array)
#2 ../Local/test/app/public/wp-includes/class-wp-http.php(614): WP_Http->request('https://api.wor...', Array)
#3 ../Local/test/app/public/wp-includes/http.php(179): WP_Http->post('https://api.wor...', Array)
#4 ../Local/test/app/public/wp-includes/update.php(404): wp_remote_post('https://api.wor...', Array)
#5 ../Local/test/app/public/wp-includes/class-wp-hook.php(303): wp_update_plugins('')
#6 ../Local/test/app/public/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters(' in ../Local/test/app/public/wp-includes/Requests/Requests.php on line 682
```

* Looking at the filesystem in `wp-includes/Requests/` folder. Files are missing ⚠️ 
   * `wp-includes/Requests/IdnaEncoder.php`
   * `wp-includes/Requests/Ipv6.php`
   * `wp-includes/Requests/Iri.php`
   * `wp-includes/Requests/Ssl.php`
   * `wp-includes/Requests/Exception/Http.php`
   * `wp-includes/Requests/Proxy/Http.php`
   * `wp-includes/Requests/Transport/Curl.php`
   * `wp-includes/Requests/Transport/Fsockopen.php`

👉  This problem is not limited to Windows OS. It's also happening on macOS.

**Comment by wojsmol** [comment]
@hellofromtonya AFAIK MacOS filesystem is case-insensitive by default

**Comment by pbiron** [comment]
> 👉 This problem is not limited to Windows OS. It's also happening on macOS.

Thanx @hellofromtonya , I was going to make that remark as well.  While I don't have a macOS machine, my understanding is that it's filesystem is also case-insensitive, but is case-preserving (i.e., you if you create a file named `Foo.php` it will always display with the initi-cap, but you can't have both `foo.php` and 'Foo.php' in the same directory).

So, yes, the problem does affect Mac's as well as Windows machines.

**Comment by pbiron** [comment]
I hope to have a PR for this by tomorrow.

**Comment by pbiron** [comment]
@costdev pointed out to me (in Slack DM) that the `wp core verify-checksums` command has a similar `compare filenames in the current install with what the checksums API returns` functionality [here](https://github.com/wp-cli/checksum-command/blob/2e7640bb28c54c229fbcdeee1c77d029b86ac7be/src/Checksum_Core_Command.php#L116).

While I hadn't know about that command until Colin pointed me to it, looking at it I think the same case folding should be applied there as in the PR for this issue.

The question is: since that command is in a different class/package, does it make sense to add a public function that is available to all of wp-cli (e.g., in the `WP_CLI\Utils` namespace) and call that in both commands?

@schlessera  any thoughts?
